name: Alexander Furones
linkedin: https://www.linkedin.com/in/alexander-furones
github: alexfuro
github_url: https://www.github.com/alexfuro
email: afurones43@gmail.com
description: Alex is building anything that comes to his mind with whatever technology he can get his hands on.

collections:
  projects:

defaults:
  scope:
    path: "/projects"
    type: projects
  values:
    layout: default
